Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -17,6 +17,7 @@ jobs:
       uses: docker/setup-buildx-action@v2
 
     - name: Authenticate to Google Cloud
+
       uses: google-github-actions/auth@v2
       with:
         credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
@@ -30,8 +31,22 @@ jobs:
         docker build -t ${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/my-app:$GITHUB_SHA .
         docker tag ${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/my-app:$GITHUB_SHA ${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/my-app:latest
 
+    - name: Check Docker image size
+      id: check_size
+      run: |
+        IMAGE_SIZE=$(docker image inspect ${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/my-app:$GITHUB_SHA --format='{{.Size}}')
+        IMAGE_SIZE_MB=$(echo "scale=2; $IMAGE_SIZE/1024/1024" | bc)
+        echo "Docker image size: $IMAGE_SIZE_MB MB"
+        echo "::set-output name=image_size::$IMAGE_SIZE_MB"
+
+    - name: Fail if image size exceeds 500MB
+      if: steps.check_size.outputs.image_size > 500
+      run: |
+        echo "Image size exceeds the limit of 500MB. Failing the job."
+        exit 1
     - name: Push the Docker image to GCR
-      run: 
+      run: |
+        # Pousser l'image avec le tag SHA
         docker push ${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/my-app:$GITHUB_SHA
 
     - name: Logout from GCR
